### PR TITLE
feat: Allow SQS port number to be passed as environmental configuration

### PR DESCRIPTION
**Pull request by ahmedelbougha**
Please refer to **#659 SQS Port as Env. Configuration** for more details.

### CODE REVIEW

**Review by seb-cr — CHANGES_REQUESTED** [review]
Makes sense, thanks for doing this!

I wondered about allowing the port number to be included in `LAMBDA_WRAPPER_OFFLINE_SQS_HOST`, e.g. `localhost:4566`, so that we avoid another SQS config variable. However I think this would be harder to implement in a backwards compatible way, so I'm happy with your approach.

Three more small things needed here:

- Please add a test for this in `tests/unit/Service/SQS.service.test.js`. There's a suite of queue URL tests in there.
- Also add a note to the readme documenting use of `LAMBDA_WRAPPER_OFFLINE_SQS_PORT`. This can go in the [Local SQS mode](https://github.com/comicrelief/lambda-wrapper/blob/master/README.md#local-sqs-mode) section.
- Finally, you'll need to prefix your PR title with `feat:` so that `semantic-release` publishes this when merged.

**Comment by ahmedelbougha** [comment]
Thanks @seb-cr for comprehensive review and comments.
I have implemented the comments you mentioned.

**Comment by seb-cr** [comment]
> Thanks @seb-cr for comprehensive review and comments. I have implemented the comments you mentioned.

Great, thank you!

Just checking your tests, they need to be slightly more robust – I can make them fail if I set `LAMBDA_WRAPPER_OFFLINE_SQS_PORT` in my terminal. Try running this:

```
$ LAMBDA_WRAPPER_OFFLINE_SQS_PORT=1234 yarn test tests/unit/Service/SQS.service.test.js
```

Make sure at the start of each test you `delete` any environment variables that you expect to be unset.

There are also `beforeAll` and `afterAll` hooks at the top of the suite that save and restore the `process.env` values that get set/deleted by the tests. `LAMBDA_WRAPPER_OFFLINE_SQS_PORT` and `LAMBDA_WRAPPER_OFFLINE_SQS_HOST` should be added there.

**Comment by ahmedelbougha** [comment]
Great @seb-cr, I have implemented that as well.

**Pull request merged**
